create table lonartkat_ro 
  (
    kat_rednr nchar(4) not null ,
    kat_lart nchar(4) not null ,
    kat_giltdat nchar(8) not null ,
    kat_lartgrp nchar(2),
    kat_from nchar(1),
    kat_tom nchar(1),
    kat_ant nchar(1),
    kat_apris nchar(1),
    kat_belopp nchar(1),
    kat_framdat nchar(1),
    kat_lat nchar(1),
    kat_lamin nchar(1),
    kat_labelopp decimal(7,2),
    kat_laneg nchar(1),
    kat_tjomf nchar(1),
    kat_ladiv1 nchar(1),
    kat_ladiv2 decimal(5),
    kat_lamult1 decimal(7,3),
    kat_lapen nchar(1),
    kat_retro nchar(1),
    kat_lareda nchar(1),
    kat_laredb nchar(1),
    kat_laredc nchar(1),
    kat_laredi nchar(1),
    kat_laredsjuk nchar(1),
    kat_laredsem nchar(1),
    kat_laredvik nchar(1),
    kat_lapri nchar(1),
    kat_laskatt nchar(1),
    kat_laink nchar(1),
    kat_laund nchar(1),
    kat_lapension nchar(1),
    kat_laack1 nchar(1),
    kat_laack2 nchar(1),
    kat_laack3 nchar(2),
    kat_labciy nchar(1),
    kat_latidsbegr nchar(5),
    kat_semdisk decimal(5,0),
    kat_specbeh nchar(1),
    kat_labegr nchar(2),
    kat_lalkp nchar(1),
    kat_lamotkont nchar(3),
    kat_lafben nchar(20),
    kat_andr nchar(1),
    retrokod nchar(1),
    resgrupp nchar(1),
    moms decimal(5,3),
    dat_tom nchar(8),
    matrkod_civ nchar(2),
    matrkod_mil nchar(2),
    pa03kod nchar(2),
    forskottflag smallint,
    dubbelanst smallint,
    dubbelfordel smallint,
    ejnetto nchar(1),
    aktuell nchar(1),
    genererad smallint,
    sd_grupp nchar(3),
    constraint pk_lonartkat_ro primary key (kat_rednr,kat_lart,kat_giltdat)  
  );
  
  GO