create table personack 
  (
    rednr nchar(4) not null ,
    penr nchar(12) not null ,
    p_bil decimal(10,2),
    p_kost decimal(10,2),
    p_bost decimal(10,2),
    p_drivmedel decimal(10,2),
    p_annan decimal(10,2),
    p_atphem decimal(10,2),
    p_ejatp decimal(10,2),
    p_egenavg decimal(10,2),
    p_form decimal(10,2),
    p_kers decimal(10,2),
    p_antkm decimal(10,2),
    p_bilkryss nchar(1),
    p_traktkryss nchar(1),
    p_utrikkryss nchar(1),
    p_kerskryss nchar(1),
    p_logikryss nchar(1),
    p_reprkryss nchar(1),
    inrik_ef_3_man nchar(1),
    utrik_ef_3_man nchar(1),
    hink nchar(1),
    skattetyp nchar(1),
    skattetab decimal(5,2),
    kol nchar(1),
    procskatt decimal(5,2),
    engsk decimal(5,2),
    jamkningskod nchar(1),
    jamkbelopp integer,
    p_kvskatt nchar(1),
    kvarskattbel integer,
    dragterm7 decimal(7),
    jamkgrans decimal(10,2),
    jamkproc decimal(5,2),
    jamkfm nchar(8),
    jamktm nchar(8),
    ansarstat nchar(8),
    anstdat nchar(8),
    kallort nchar(1),
    arbnr nchar(5),
    aprelskatt decimal(7),
    p_prellan1 nchar(2),
    p_prelkom1 nchar(2),
    p_prelfors1 nchar(2),
    fel nchar(1),
    ber_flag nchar(1),
    sem_flag nchar(1),
    tab_flag nchar(1),
    lonutbman nchar(12),
    m_brutto decimal(10,2),
    m_belskatt decimal(10,2),
    m_intresse decimal(10,2),
    m_prelskatt decimal(7),
    m_kvarskatt decimal(7),
    m_netto decimal(10,2),
    m_egen_brutto decimal(10),
    m_kers_brutto decimal(10,2),
    p_bilkod nchar(7),
    hogrisk nchar(1),
    direkt_flag nchar(1),
    arbetsland nchar(3),
    utsandningstid nchar(1),
    kodgul nchar(1),
    forbindelsenr nchar(20),
    ku_flag nchar(1)
  );
  
  GO