create table resenar 
  (
    rednr nchar(4) not null ,
    reseid integer not null ,
    koncernkod nchar(3) not null ,
    grupp nchar(10) not null ,
    penr nchar(12),
    anstlpnr nchar(1),
    statres smallint not null ,
    statdat datetime,
    skaphandl nchar(20),
    skapdat datetime,
    reshandl nchar(20),
    postlas nchar(1),
    urval nchar(10),
    urvalgodk nchar(1),
    godkhandl nchar(20),
    fortyp nchar(2),
    resa_fdat datetime,
    resa_tdat datetime,
    reskategori nchar(2) not null ,
    attesterare nchar(20),
    attestdatum nchar(8),
    system nchar(3),
    status nchar(1),
    lasthandl nchar(20),
    lastdatum datetime,
    prelslutl smallint,
    prelhandl nchar(20),
    prelber date,
    pamindat datetime,
    loneavdrdat datetime,
    org nchar(10),
    avtalstyp nchar(1),
    resezon nchar(2),
    constraint pk_resenar primary key (rednr,reseid)  
  );
  
  GO