create table resenar 
  (
	rednr nchar(4) not null ,
    reseid integer not null ,
    koncernkod nchar(3) not null ,
    penr nchar(12),
    anstlpnr nchar(1),
    statres smallint not null ,
    statdat date,
    skaphandl nchar(20),
    skapdat date,
    reshandl nchar(20),
    postlas nchar(1),
    urval nchar(10),
    urvalgodk nchar(1),
    godkhandl nchar(20),
    fortyp nchar(2),
    resa_fdat date,
    resa_tdat date,
    reskategori nchar(2) not null ,
    attesterare nchar(20),
    attestdatum nchar(8),
    system nchar(3),
    status nchar(1),
    lasthandl nchar(20),
    lastdatum date,
    prelslutl smallint,
    prelhandl nchar(20),
    prelber date,
    pamindat date,
    loneavdrdat date,
    org nchar(10),
    avtalstyp nchar(1),
    resezon nchar(2),
    maltid nchar(1),
    antecklpnr smallint,
    stattid nchar(5),
    skaptid nchar(5),
    resa_ftid nchar(5),
    resa_ttid nchar(5),
    lasttid nchar(5),
    berlas nchar(1),
	constraint pk_resenar primary key (rednr,reseid)  
  );
  
  GO